In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
# Load dataset Iris dari scikit-learn
iris = load_iris()

Kode ini digunakan untuk mengimpor library yang diperlukan dan mengambil dataset Iris. numpy digunakan untuk mengolah data dalam bentuk array, sedangkan pandas digunakan untuk mengelola data dalam bentuk tabel/DataFrame. load_iris digunakan untuk mengambil dataset Iris yang sudah tersedia di scikit-learn, kemudian iris = load_iris() menyimpan dataset tersebut ke dalam variabel iris agar dapat digunakan pada tahap selanjutnya.

In [2]:
# Konversi data menjadi DataFrame Pandas
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["Species"] = iris.target_names[iris.target]
# Definisikan X (fitur) dan y (target/label)
X = df.drop(columns=["Species"])
y = df["Species"]
print(X)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


Kode ini digunakan untuk mengubah dataset Iris menjadi DataFrame dan memisahkan data fitur dengan target. pd.DataFrame() membuat tabel dari data Iris dengan nama kolom sesuai fitur Iris. Kolom Species ditambahkan untuk menyimpan nama jenis bunga. Kemudian X berisi fitur-fitur bunga tanpa kolom Species, sedangkan y berisi target atau jenis bunga Iris. print(X) digunakan untuk menampilkan data fitur yang akan digunakan dalam proses klasifikasi.

In [3]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: str

y digunakan untuk menentukan target atau label yang akan diprediksi. Variabel y mengambil kolom Species dari DataFrame df, yang berisi jenis bunga Iris seperti setosa, versicolor, dan virginica. Jadi, y merupakan data target yang akan digunakan oleh model klasifikasi.

In [4]:
from sklearn.preprocessing import LabelEncoder
lab = LabelEncoder()
y = lab.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Kode ini digunakan untuk mengubah label species yang awalnya berupa teks menjadi angka agar dapat diproses oleh algoritma Naive Bayes. LabelEncoder() melakukan proses encoding pada y, sehingga label seperti setosa, versicolor, dan virginica diubah menjadi nilai numerik 0, 1, dan 2. Hasil encoding kemudian disimpan kembali ke y dan ditampilkan.

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test = train_test_split(X, test_size=0.2, random_state=0)
y_train, y_test = train_test_split(y, test_size=0.2, random_state=0)

Kode ini digunakan untuk membagi data menjadi data training dan data testing. test_size=0.2 berarti 20% data digunakan untuk testing dan 80% untuk training, sedangkan random_state=0 digunakan agar pembagian data tetap sama setiap kali kode dijalankan. X_train dan y_train digunakan untuk melatih model, sedangkan X_test dan y_test digunakan untuk menguji hasil prediksi model.

In [6]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
NB_model = model.fit(X_train, y_train)

Kode ini digunakan untuk membuat dan melatih model Gaussian Naive Bayes. GaussianNB() membuat model Naive Bayes yang sesuai untuk data numerik kontinu seperti dataset Iris. Kemudian model.fit(X_train, y_train) melatih model menggunakan data training X_train dan label y_train, lalu model yang sudah dilatih disimpan dalam variabel NB_model.

In [7]:
result = NB_model.predict(X_test)
result

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

Kode ini digunakan untuk memprediksi kelas/species dari data testing menggunakan model NB_model yang sudah dilatih sebelumnya. NB_model.predict(X_test) menghasilkan prediksi untuk setiap data pada X_test, kemudian hasilnya disimpan dalam variabel result dan ditampilkan.

In [8]:
from sklearn.metrics import accuracy_score
print('Accuracy of data testing: ', accuracy_score(y_test, result)*100)

Accuracy of data testing:  96.66666666666667


Kode ini digunakan untuk menghitung tingkat akurasi model berdasarkan hasil prediksi result dan data sebenarnya y_test. accuracy_score() membandingkan keduanya, kemudian dikalikan 100 agar hasil akurasi ditampilkan dalam bentuk persentase. Pada modul, hasil akurasi data testing adalah sekitar 96,67%.

In [9]:
#prediksi inputan data baru
#input_data = pd.DataFrame(np.array([[5.1, 3.5, 1.4, 0.2]]), columns=iris.feature_names)
input_data = [[5.1, 3.5, 1.4, 0.2]]
result = NB_model.predict(input_data)
prediction_label = lab.inverse_transform(result)
print('Hasil prediksi untuk input baru adalah:', prediction_label)

Hasil prediksi untuk input baru adalah: ['setosa']


c:\Users\Greis Juniwaty\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


Kode ini digunakan untuk memprediksi species dari data Iris baru menggunakan model NB_model yang sudah dilatih. input_data berisi 4 nilai fitur bunga, kemudian NB_model.predict() menentukan kelasnya. Hasil prediksi yang awalnya berupa angka diubah kembali menjadi nama species menggunakan lab.inverse_transform(). Untuk input [5.1, 3.5, 1.4, 0.2], hasil prediksinya adalah setosa.

In [10]:
input_data = pd.DataFrame(np.array([[5.1, 3.5, 1.4, 0.2]]), columns=iris.feature_names)
result = NB_model.predict(input_data)
prediction_label = lab.inverse_transform(result)
print('Hasil prediksi untuk input baru adalah:', prediction_label)

Hasil prediksi untuk input baru adalah: ['setosa']


Kode ini digunakan untuk memprediksi species dari data Iris baru dengan format DataFrame. pd.DataFrame() membuat input memiliki nama kolom yang sama dengan fitur dataset Iris, kemudian NB_model.predict() melakukan prediksi. Hasil prediksi yang masih berupa angka diubah kembali menjadi nama species menggunakan lab.inverse_transform(). Untuk input tersebut, hasilnya adalah setosa. Cara ini juga digunakan dalam modul agar struktur input konsisten dengan data yang digunakan saat model dilatih.

In [11]:
#TUGAS 
#Input data baru
input_data = pd.DataFrame(
    np.array([[7.3, 3.8, 4.6, 2.3]]),
    columns=iris.feature_names
)

input_data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,7.3,3.8,4.6,2.3


Kode ini digunakan untuk membuat data baru yang akan diprediksi oleh model. np.array() menyimpan nilai fitur [7.3, 3.8, 4.6, 2.3], kemudian pd.DataFrame() mengubahnya menjadi tabel dengan nama kolom sesuai fitur dataset Iris. input_data digunakan sebagai data masukan untuk proses prediksi species pada tahap berikutnya.

In [12]:
#Prediksi data baru
result = NB_model.predict(input_data)
result

array([2])

Kode ini digunakan untuk memprediksi species dari data baru yang sudah disimpan dalam input_data. NB_model.predict(input_data) menjalankan data tersebut melalui model Gaussian Naïve Bayes yang sudah dilatih, kemudian hasil prediksinya disimpan dalam variabel result.

Untuk data [7.3, 3.8, 4.6, 2.3], result akan menghasilkan kode kelas. Selanjutnya, kode tersebut perlu diubah menjadi nama species menggunakan lab.inverse_transform().

In [13]:
#Mengubah hasil menjadi nama spesies
prediction_label = lab.inverse_transform(result)

print(
    'Hasil prediksi untuk input baru adalah:',
    prediction_label
)

Hasil prediksi untuk input baru adalah: ['virginica']


Kode ini digunakan untuk mengubah hasil prediksi yang masih berupa angka menjadi nama species Iris. lab.inverse_transform(result) mengembalikan label angka menjadi nama species seperti setosa, versicolor, atau virginica. Kemudian print() menampilkan hasil prediksi tersebut.

Untuk input [7.3, 3.8, 4.6, 2.3], hasil prediksinya adalah versicolor.